name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - '5432:5432'
        options: >-
          --health-cmd="pg_isready -U test -d test_db"
          --health-interval=10s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run backend tests
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test_db
        run: pytest --maxfail=1 --disable-warnings -q
